import { Post } from '@/types';

export const TAGS: Post['tag'][] = ['전체', '공유해요', '공감원해요', '함께해요', '고수찾아요'];

export const DUMMY_POSTS: Post[] = [
  {
    id: '1',
    tag: '공유해요',
    title: 'ADHD 아이 훈육 팁 공유해요',
    content: '저희 아이는 이렇게 하니 정말 효과가 좋았어요. 우선 아이의 눈을 보고...',
    author: '육아고수맘',
    like: 23,
    comment: 7,
    views: 142,
  },
  {
    id: '2',
    tag: '공감원해요',
    title: '오늘 정말 힘든 하루였네요..',
    content: '마트에서 아이가 소리를 질러서 너무 당황스러웠어요. 다들 이런 경험 있으시죠?',
    author: '지친하루',
    like: 15,
    comment: 4,
    views: 210,
  },
  {
    id: '3',
    tag: '함께해요',
    title: '속상해서 그냥 털어놓아요',
    content: '주변 시선이 너무 따가워서 눈물이 났어요. 누가 그냥 들어줬으면 좋겠어요. 답은 필요 없어요.',
    author: '토닥토닥',
    like: 8,
    comment: 2,
    views: 98,
  },
  {
    id: '4',
    tag: '고수찾아요',
    title: '정부 지원금 신청 방법 아시는 분?',
    content: '이번에 새로 나온 지원금이 있다고 하던데, 어떻게 신청해야 하나요? 홈페이지 주소 아시는 분...',
    author: '정보요정',
    like: 31,
    comment: 10,
    views: 325,
  },
  {
    id: '5',
    tag: '고수찾아요',
    title: '아니 이거 어떻게 하셨어요?',
    content: '오늘 상담하러 갔는데 어떤 고수 분께서 아이를 잘 다루시더라구요. 어쩜 그리 말을 잘듣는지...',
    author: '정보요정',
    like: 19,
    comment: 6,
    views: 178,
  },
  {
    id: '6',
    tag: '공유해요',
    title: '상담 받아보신 분 후기 남겨주세요.',
    content: '주기적으로 상담을 받으러 가시는 분들 중에서 꾸준히 나아지고 있는지 궁금해요...',
    author: '정보요정',
    like: 12,
    comment: 3,
    views: 120,
  },
  {
    id: '7',
    tag: '공유해요',
    title: '자폐 아동 보호자, 나도 이것 할 수 있다?',
    content: '지치고 힘든 일상, 우리도 여유를 내며 시간을 가질 수 있다면 믿으시겠습니까?...',
    author: '정보요정',
    like: 27,
    comment: 8,
    views: 260,
  },
  {
    id: '8',
    tag: '함께해요',
    title: '나눔합니다. 가져가세요!',
    content: '이번에 새로 나온 지원금이 있다고 하던데, 어떻게 신청해야 하나요? 홈페이지 주소 아시는 분...',
    author: '정보요정',
    like: 5,
    comment: 1,
    views: 75,
  },
  {
    id: '9',
    tag: '공감원해요',
    title: '오늘 너무 스트레스 받았아요. 위로 부탁해요.',
    content: '아이와 함께 하는 시간이 이렇게 힘들 줄 몰랐어요. 아무것도 내 마음대로 되지 않는 것 같네요...',
    author: '정보요정',
    like: 44,
    comment: 12,
    views: 401,
  },
  {
    id: '10',
    tag: '공감원해요',
    title: '이게 뭐에요?',
    content: '이게 이게 뭐에요? 이게 뭐에요? 이게 이게 뭐에요? 이게 뭐에요? 이게 이게 뭐에요? 이게 뭐에요...',
    author: '정보요정',
    like: 17,
    comment: 5,
    views: 190,
  },
];
